### ISSUE TITLE
Author Setting wird nicht auf Über mich Seite angewendet

### ISSUE THREAD

**Issue by RolandStuder** [marcojakob/lilo-blog#1]
Wen wir schon das Author Setting haben, dann sollte es auch als Default, z. B. auf Über mich und beim Seitentitel verwendet werden. Ich muss initital meinen Namen etwa an vier Orten eingeben.

**Comment by marcojakob** [comment]
Das ist absichtlich so gemacht, dass man auch flexibel andere Inhalte an diesen Stellen erfassen könnte. Ist also eher ein Feature als ein Bug... ;-)
