### ISSUE TITLE
Featured Image sollte optional sein

### ISSUE THREAD

**Issue by marcojakob** [marcojakob/lilo-blog#2]
@RolandStuder bemerkt, dass es möglich sein sollte, einen Blogartikel zu erfassen ohne ein Bild bereit zu haben.

Siehe dieses Bild
![image](https://user-images.githubusercontent.com/2089493/58797226-c0d74980-85ff-11e9-9c34-7d3088f3fa9d.png)

**Comment by marcojakob** [comment]
Ab Lernblog Version 1.0.2 ist dies nun möglich.

**Comment by RolandStuder** [comment]
Thx, jetzt hast du mir aber die Möglichkeit genommen einen Pull Request dafür zu machen.

**Comment by RolandStuder** [comment]
Den Header auf der Startseite ist aber in dieser Version noch nicht so, im netlify-cms config, ist das Hauptbild noch immer required, wenn man es manuell im Code löscht, kommt einfach der Schwarze Hintergrund.

**Comment by marcojakob** [comment]
@RolandStuder Jetzt sind alle Bilder in den Einstellungen auch optional.

PS: Für ein Update alles löschen bis auf den `content` Ordner und mit der neuen Version ersetzen.
