### ISSUE TITLE
Custom CSS in Content Ordner

### ISSUE THREAD

**Issue by RolandStuder** [marcojakob/lilo-blog#3]
Manchmal würde ich gerne mein CSS anpassen, aber dann denke ich, wenn ich updaten will verliere ich dies. Vielleicht sollte man eine Strategie entwickeln, wie man Custom Dinge doch zulassen kann, die Bilder werden ja, z. B. auch im Content Ordner abgelegt. wie wäre es auch einen Ordner mit `styles` oder `css` zu haben, mit einem leeren css oder scss file, dass aber beim Builden automatisch schon inkludiert ist.

Was meinst du? Könnte dir dafür eine Pull Request machen.

**Comment by marcojakob** [comment]
Es gibt im CMS unter `Einstellungen/Code` ein Header und Footer Code-Bereich. Dort könntest du `<style></style>` tags reinfüllen. Das ist dann die Datei `content/settings/code/index.md`. Wenn du dort mit dem Code-Editor das CSS bearbeiten willst, würde ich mit Multiline-Markdown Strings arbeiten. Das sähe dann so aus:
```
siteHeader = """
<style>
.meinStyle {

}
</style>
"""
```



PS: Bei Hugo gäbe es genau diesen Mechanismus mit Themes. Aber das macht die Struktur einiges komplizierter, weshalb ich mich dagegen entschieden habe.

**Comment by marcojakob** [comment]
I'm closing this since it is already possible to add custom CSS through the CMS (via `Settings/Code`).
